version: '3.9'

services:
  postgres:
    image: postgres:14.12
    container_name: duckbot_postgres
    restart: always
    healthcheck:
      test: "exit 0"
    ports:
      - 5439:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duckbot_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-compose.sql:/docker-entrypoint-initdb.d/init.sql
    # uncomment below if you want to log queries
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes:
  postgres_data: {}
