from telegram.ext import (
  ConversationHandler,
)

MARKET_MAKER_TG_ID = 7210638562

END = ConversationHandler.END

# Stages
QUERY_ROUTES, EXPLORER_ROUTES, WALLET_ROUTES, TRADE_ROUTES, PREDICTION_ROUTES, END_ROUTES = range(6)

(
  MAIN_MENU,
  TRADE_MANAGEMENT,
  WALLET_MANAGEMENT,
  EXPLORER_MANAGEMENT,
  TRADE_MANAGEMENT,
  PREDICTION_MANAGEMENT,
  NETWORK_INFO,
  BALANCE,
  ERC20BALANCE,
  GEN_WALLET,
  FUND_WALLET,
  PRIVATE_KEY,
  SEND_FUNDS,
  FETCH_BRIDGE_INFO,
  SELECT_MARKET,
  CATEGORY,
) = range(16)





