"""create_wallet_table

Revision ID: 9e8a59dcf5c7
Revises: 7937534aa760
Create Date: 2024-09-20 22:52:40.679754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9e8a59dcf5c7'
down_revision: Union[str, None] = '7937534aa760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('encrypted_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_user_id', 'address')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
    
